apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kittenapi
  name: kittenapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kittenapi
  template:
    metadata:
      labels:
        app: kittenapi
    spec:
      containers:
      - image: nginx
        name: nginx
